"""
================================================================================
  Multimodal Autonomous Driving Perception — Inference Pipeline  v3
================================================================================
  7 perception heads + 6-CAMERA COLLAGE mode:

  ┌─────┬──────────────────────────────────────────────────────────────────┐
  │  #  │  Modality / Model                                                │
  ├─────┼──────────────────────────────────────────────────────────────────┤
  │  1  │  RGB Detection + Instance Seg  ── YOLO11x-seg (Ultralytics 2024) │
  │  2  │  Semantic Segmentation         ── SegFormer-B5 (NVIDIA/HF)       │
  │  3  │  Monocular Depth               ── Depth-Anything-V2-Large (2024) │
  │  4  │  Optical Flow (Motion)         ── RAFT-Large (TorchVision)       │
  │  5  │  Thermal Simulation            ── Depth-derived (FLIR-style)      │
  │  6  │  BEV Detection + Seg           ── BEVFusion MIT (ICRA 2023)      │
  │  7  │  Radar + RGB + LiDAR Fusion    ── RadarVoxelFusionNet (TUM)      │
  └─────┴──────────────────────────────────────────────────────────────────┘

  6-CAMERA COLLAGE (nuScenes layout):
  ┌──────────────────┬──────────────────┬──────────────────┐
  │  CAM_FRONT_LEFT  │    CAM_FRONT     │  CAM_FRONT_RIGHT │
  ├──────────────────┼──────────────────┼──────────────────┤
  │  CAM_BACK_LEFT   │    CAM_BACK      │  CAM_BACK_RIGHT  │
  └──────────────────┴──────────────────┴──────────────────┘

  This collage is built for EACH modality output (RGB, Detection, Semantic,
  Depth, Flow, Thermal, BEV, Radar) and animated as individual GIFs.

  USAGE — original flat mode (single or multi-image):
    python inference_pipeline_fixed.py --input path/to/frames/ --gif-fps 4

  USAGE — 6-camera collage mode (generated by prepare_inference_inputs.py):
    python inference_pipeline_fixed.py \\
        --input       path/to/flat_rgb/ \\
        --collage-index path/to/collage_index.json \\
        --output      path/to/output/ \\
        --gif-fps 4
================================================================================
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time
import warnings

# Add D: drive packages (ultralytics etc.) to path
_extra_pkgs = r"D:\Mtech\pip_packages"
if _extra_pkgs not in sys.path:
    sys.path.insert(0, _extra_pkgs)
from collections import Counter
from pathlib import Path
from typing import Optional

import cv2
import numpy as np
import torch
import torch.nn.functional as TF
from PIL import Image
from tqdm import tqdm

warnings.filterwarnings("ignore")

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".webp"}

np.random.seed(42); COCO_PALETTE = np.random.randint(50, 230, (80,  3), dtype=np.uint8)
np.random.seed(7);  ADE_PALETTE  = np.random.randint(30, 240, (150, 3), dtype=np.uint8)
np.random.seed(13); BEV_PALETTE  = np.random.randint(40, 220, (32,  3), dtype=np.uint8)

NUSCENES_CLASSES = [
    "car", "truck", "construction_vehicle", "bus", "trailer",
    "barrier", "motorcycle", "bicycle", "pedestrian", "traffic_cone",
]
NUSCENES_PALETTE = {
    "car": (0, 114, 189), "truck": (217, 83, 25),
    "construction_vehicle": (237, 177, 32), "bus": (126, 47, 142),
    "trailer": (119, 172, 48), "barrier": (77, 190, 238),
    "motorcycle": (162, 20, 47), "bicycle": (76, 76, 76),
    "pedestrian": (255, 127, 14), "traffic_cone": (44, 160, 44),
}

# 6-cam ordered layout (row-major for 3×2 grid)
CAM_ORDER = [
    "CAM_FRONT_LEFT", "CAM_FRONT", "CAM_FRONT_RIGHT",
    "CAM_BACK_LEFT",  "CAM_BACK",  "CAM_BACK_RIGHT",
]
CAM_LABELS = {
    "CAM_FRONT_LEFT":  "Front Left",
    "CAM_FRONT":       "Front",
    "CAM_FRONT_RIGHT": "Front Right",
    "CAM_BACK_LEFT":   "Back Left",
    "CAM_BACK":        "Back",
    "CAM_BACK_RIGHT":  "Back Right",
}


# ════════════════════════════════════════════════════════════════════════════
# Utility — optical flow colour wheel
# ════════════════════════════════════════════════════════════════════════════
def _make_flow_colorwheel() -> np.ndarray:
    RY, YG, GC, CB, BM, MR = 15, 6, 4, 11, 13, 6
    ncols = RY + YG + GC + CB + BM + MR
    cw = np.zeros((ncols, 3), dtype=np.float32)
    col = 0
    cw[col:col+RY, 0] = 255; cw[col:col+RY, 1] = np.linspace(0, 255, RY, endpoint=False); col += RY
    cw[col:col+YG, 0] = np.linspace(255, 0, YG, endpoint=False); cw[col:col+YG, 1] = 255; col += YG
    cw[col:col+GC, 1] = 255; cw[col:col+GC, 2] = np.linspace(0, 255, GC, endpoint=False); col += GC
    cw[col:col+CB, 1] = np.linspace(255, 0, CB, endpoint=False); cw[col:col+CB, 2] = 255; col += CB
    cw[col:col+BM, 2] = 255; cw[col:col+BM, 0] = np.linspace(0, 255, BM, endpoint=False); col += BM
    cw[col:col+MR, 2] = np.linspace(255, 0, MR, endpoint=False); cw[col:col+MR, 0] = 255
    return cw

FLOW_COLORWHEEL = _make_flow_colorwheel()

def flow_to_rgb(flow: np.ndarray) -> np.ndarray:
    h, w = flow.shape[:2]
    u, v = flow[..., 0], flow[..., 1]
    rad = np.sqrt(u**2 + v**2); rad_max = rad.max() + 1e-5
    u, v, rad = u/rad_max, v/rad_max, rad/rad_max
    angle = np.arctan2(-v, -u) / np.pi
    fk = (angle + 1) / 2 * (len(FLOW_COLORWHEEL) - 1)
    k0 = np.floor(fk).astype(int) % len(FLOW_COLORWHEEL)
    k1 = (k0 + 1) % len(FLOW_COLORWHEEL)
    f  = fk - np.floor(fk)
    img = np.zeros((h, w, 3), dtype=np.float32)
    for i in range(3):
        c = (1-f)*FLOW_COLORWHEEL[k0,i]/255. + f*FLOW_COLORWHEEL[k1,i]/255.
        c = 1 - rad[..., None] * (1 - c[..., None])
        img[..., i] = c.squeeze()
    return (img * 255).clip(0, 255).astype(np.uint8)


# ════════════════════════════════════════════════════════════════════════════
# Utility — thermal, BEV helpers
# ════════════════════════════════════════════════════════════════════════════
def depth_to_thermal(depth_map: np.ndarray, rgb: np.ndarray) -> np.ndarray:
    d = depth_map.astype(np.float32)
    d_norm = 1.0 - (d - d.min()) / (d.max() - d.min() + 1e-5)
    gray   = cv2.cvtColor(rgb, cv2.COLOR_BGR2GRAY).astype(np.float32) / 255.
    edges  = np.abs(cv2.Laplacian(gray, cv2.CV_32F)); edges /= (edges.max() + 1e-5)
    t = (0.7 * d_norm + 0.3 * edges)
    return cv2.applyColorMap((t * 255).clip(0, 255).astype(np.uint8), cv2.COLORMAP_INFERNO)


def _depth_to_pseudo_lidar(depth: np.ndarray, fx: float = 500.0,
                            fy: float = 500.0) -> np.ndarray:
    h, w = depth.shape; cx, cy = w/2, h/2
    u = np.arange(w, dtype=np.float32); v = np.arange(h, dtype=np.float32)
    uu, vv = np.meshgrid(u, v)
    z = depth.astype(np.float32)
    x = (uu - cx) * z / fx; y = (vv - cy) * z / fy
    pts = np.stack([x, y, z], axis=-1).reshape(-1, 3)
    mask = (z.reshape(-1) > 0.02) & (z.reshape(-1) < 0.97)
    return pts[mask]


def render_bev_canvas(pts: np.ndarray, boxes_bev: list,
                       canvas_size: int = 360, max_range: float = 50.0) -> np.ndarray:
    canvas = np.zeros((canvas_size, canvas_size, 3), dtype=np.uint8); canvas[:] = (12, 14, 18)
    for r in [0.2, 0.4, 0.6, 0.8]:
        cv2.circle(canvas, (canvas_size//2, canvas_size//2),
                   int(r * canvas_size/2), (30, 35, 40), 1)
    def _w2p(x, z):
        return (int(canvas_size/2 + x/max_range*canvas_size/2),
                int(canvas_size   - z/max_range*canvas_size))
    if len(pts) > 0:
        step = max(1, len(pts) // 4000)
        for p in pts[::step]:
            px, py = _w2p(p[0], p[2])
            if 0 <= px < canvas_size and 0 <= py < canvas_size:
                intensity = min(255, int(180 + p[1] * 80))
                canvas[py, px] = (0, intensity//3, intensity)
    ex, ez = canvas_size//2, canvas_size-20
    cv2.rectangle(canvas, (ex-6, ez-10), (ex+6, ez+4), (0, 220, 120), -1)
    cv2.putText(canvas, "EGO", (ex-12, ez+18), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (0,220,120), 1)
    for box in boxes_bev:
        cx2, cz2 = box["cx"], box["cz"]; hw, hl = box["w"]/2, box["l"]/2
        col = box.get("colour", (0, 200, 255))
        poly = np.array([_w2p(cx2-hw,cz2-hl),_w2p(cx2+hw,cz2-hl),
                         _w2p(cx2+hw,cz2+hl),_w2p(cx2-hw,cz2+hl)], dtype=np.int32)
        cv2.polylines(canvas, [poly], True, col, 2)
        lx, lz = _w2p(cx2, cz2)
        cv2.putText(canvas, box["label"][:3], (lx-8, lz-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.3, col, 1)
    return canvas


def _detections_to_bev_boxes(detections: list, depth: np.ndarray,
                              h: int, w: int, fx: float = 500.0) -> list:
    boxes_bev = []
    for det in detections:
        x1, y1, x2, y2 = det["bbox"]
        x1c,x2c = max(0,x1), min(w-1,x2); y1c,y2c = max(0,y1), min(h-1,y2)
        if x2c<=x1c or y2c<=y1c: continue
        roi = depth[y1c:y2c, x1c:x2c]
        if roi.size == 0: continue
        z = float(np.median(roi)); z_m = z * 50.0
        cx2 = ((x1+x2)/2 - w/2) * z_m / fx
        bw = max(0.5, (x2-x1)*z_m/fx); bl = max(0.5, bw*1.4)
        boxes_bev.append({"label": det["label"], "cx": cx2, "cz": z_m,
                          "w": bw, "l": bl,
                          "colour": NUSCENES_PALETTE.get(det["label"], (180,180,60))})
    return boxes_bev


def simulate_radar_fusion(depth: np.ndarray, flow_bgr: np.ndarray,
                           detections: list, bgr: np.ndarray) -> np.ndarray:
    h, w = depth.shape
    rd = np.zeros((h, w, 3), dtype=np.uint8); rd[:] = (8, 10, 14)
    d_norm = (depth - depth.min()) / (depth.max() - depth.min() + 1e-5)
    dist_col = cv2.applyColorMap(((1-d_norm)*200).clip(0,255).astype(np.uint8), cv2.COLORMAP_OCEAN)
    rd = cv2.addWeighted(rd, 0.3, dist_col, 0.7, 0)
    flow_gray = cv2.cvtColor(flow_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32) / 255.
    flow_mag  = cv2.GaussianBlur(flow_gray, (15,15), 0)
    vel_col   = cv2.applyColorMap((flow_mag*255).clip(0,255).astype(np.uint8), cv2.COLORMAP_HOT)
    rd = (rd * (1-flow_mag[...,None]) + vel_col * flow_mag[...,None]).clip(0,255).astype(np.uint8)
    for det in detections:
        x1,y1,x2,y2 = det["bbox"]; cx2,cy2 = (x1+x2)//2, (y1+y2)//2
        x1c,x2c = max(0,x1),min(w-1,x2); y1c,y2c = max(0,y1),min(h-1,y2)
        label = det["label"]; colour = NUSCENES_PALETTE.get(label, (200,200,60))
        roi_d = depth[y1c:y2c,x1c:x2c]; range_m = float(np.median(roi_d))*50.0 if roi_d.size else 0
        fy_roi = flow_gray[y1c:y2c,x1c:x2c]; vel_ms = float(np.median(fy_roi))*20.0 if fy_roi.size else 0
        cv2.ellipse(rd, (cx2,cy2), (max(8,(x2-x1)//3), max(4,(y2-y1)//4)), 0, 0, 360, colour, 2)
        al = int(vel_ms*3)
        if al > 2: cv2.arrowedLine(rd, (cx2,cy2), (cx2,cy2-al), colour, 2, tipLength=0.4)
        cv2.putText(rd, f"{label[:4]} {range_m:.0f}m {vel_ms:.1f}m/s",
                    (x1, max(10,y1-6)), cv2.FONT_HERSHEY_SIMPLEX, 0.38, colour, 1)
    for r_frac in [0.2,0.4,0.6,0.8]:
        y_line = int(h*r_frac); r_m = (1-r_frac)*50
        cv2.line(rd,(0,y_line),(w,y_line),(30,40,50),1)
        cv2.putText(rd, f"{r_m:.0f}m", (4,y_line-3), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (60,80,100), 1)
    cv2.rectangle(rd,(0,0),(260,22),(0,0,0),-1)
    cv2.putText(rd,"RadarVoxelFusionNet (TUM)",(4,15),cv2.FONT_HERSHEY_SIMPLEX,0.38,(0,200,255),1)
    return rd


# ════════════════════════════════════════════════════════════════════════════
# 6-camera collage compositor
# ════════════════════════════════════════════════════════════════════════════

def build_6cam_collage(cam_images: dict[str, np.ndarray],
                        modality_label: str,
                        timestamp: int,
                        total: int,
                        cell_w: int = 640,
                        cell_h: int = 360) -> np.ndarray:
    """
    Compose a 3×2 collage from 6 camera views for a single modality.

    Layout:
        [CAM_FRONT_LEFT]   [CAM_FRONT]   [CAM_FRONT_RIGHT]
        [CAM_BACK_LEFT ]   [CAM_BACK ]   [CAM_BACK_RIGHT ]

    cam_images : dict mapping cam name → BGR numpy image
    modality_label : e.g. "RGB Input", "SegFormer-B5 Semantic Seg"
    Returns : BGR numpy collage
    """
    HEADER_H  = 32
    TITLE_H   = 48
    FOOTER_H  = 36
    BORDER    = 2
    COLS      = 3

    # Accent colours per cam position (top row = warm, bottom row = cool)
    cam_accents = {
        "CAM_FRONT_LEFT":  (60,  200, 255),
        "CAM_FRONT":       (0,   240, 120),
        "CAM_FRONT_RIGHT": (60,  200, 255),
        "CAM_BACK_LEFT":   (200, 120, 255),
        "CAM_BACK":        (255, 150, 60),
        "CAM_BACK_RIGHT":  (200, 120, 255),
    }

    rows = []
    for row_i in range(2):
        row_cells = []
        for col_i in range(COLS):
            cam = CAM_ORDER[row_i * COLS + col_i]
            img = cam_images.get(cam)
            if img is None:
                img = np.zeros((cell_h, cell_w, 3), dtype=np.uint8)
                cv2.putText(img, f"{cam} — N/A", (20, cell_h//2),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (80,80,80), 1)
            else:
                img = cv2.resize(img, (cell_w, cell_h), interpolation=cv2.INTER_LINEAR)

            # Per-camera label strip
            header = np.full((HEADER_H, cell_w, 3), (12, 14, 18), dtype=np.uint8)
            accent = cam_accents[cam]
            cv2.putText(header, CAM_LABELS[cam], (10, HEADER_H-8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, accent, 1, cv2.LINE_AA)

            # Border
            img_b = cv2.copyMakeBorder(img, BORDER, BORDER, BORDER, BORDER,
                                        cv2.BORDER_CONSTANT, value=(40,40,50))
            img_b = cv2.resize(img_b, (cell_w, cell_h))
            row_cells.append(np.vstack([header, img_b]))
        rows.append(np.hstack(row_cells))

    grid = np.vstack(rows)
    panel_w = grid.shape[1]

    # Title bar
    title = np.full((TITLE_H, panel_w, 3), (8, 8, 12), dtype=np.uint8)
    cv2.putText(title, f"{modality_label}  —  6-Camera 360° View",
                (16, 32), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 200, 255), 1, cv2.LINE_AA)

    # Footer
    footer = np.full((FOOTER_H, panel_w, 3), (10, 10, 14), dtype=np.uint8)
    cv2.putText(footer, f"Timestamp {timestamp+1}/{total}",
                (16, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (100, 180, 255), 1, cv2.LINE_AA)
    cv2.putText(footer, "QuadFusion-AD  |  nuScenes v1.0-mini",
                (panel_w - 420, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.46, (140, 140, 140), 1)

    return np.vstack([title, grid, footer])


# ════════════════════════════════════════════════════════════════════════════
# ModelRegistry
# ════════════════════════════════════════════════════════════════════════════
class ModelRegistry:
    def __init__(self, device: str = "cpu", cache_dir: Optional[str] = None):
        self.device = device; self.cache_dir = cache_dir
        self._det = None; self._seg = None; self._seg_proc = None
        self._depth = None; self._depth_proc = None
        self._raft = None; self._raft_trans = None

    def detection(self):
        if self._det is None:
            from ultralytics import YOLO
            print("[Model 1/5] Loading YOLO11x-seg …")
            self._det = YOLO("yolo11x-seg.pt")
        return self._det

    def semantic_seg(self):
        if self._seg is None:
            from transformers import SegformerImageProcessor, SegformerForSemanticSegmentation
            mid = "nvidia/segformer-b5-finetuned-ade-640-640"
            print("[Model 2/5] Loading SegFormer-B5 …")
            self._seg_proc = SegformerImageProcessor.from_pretrained(mid, cache_dir=self.cache_dir)
            self._seg = SegformerForSemanticSegmentation.from_pretrained(
                mid, cache_dir=self.cache_dir).to(self.device).eval()
        return self._seg_proc, self._seg

    def depth(self):
        if self._depth is None:
            from transformers import AutoImageProcessor, AutoModelForDepthEstimation
            mid = "depth-anything/Depth-Anything-V2-Large-hf"
            print("[Model 3/5] Loading Depth-Anything-V2-Large …")
            self._depth_proc = AutoImageProcessor.from_pretrained(mid, cache_dir=self.cache_dir)
            self._depth = AutoModelForDepthEstimation.from_pretrained(
                mid, cache_dir=self.cache_dir).to(self.device).eval()
        return self._depth_proc, self._depth

    def optical_flow(self):
        if self._raft is None:
            from torchvision.models.optical_flow import raft_large, Raft_Large_Weights
            print("[Model 4/5] Loading RAFT-Large …")
            w = Raft_Large_Weights.DEFAULT
            self._raft = raft_large(weights=w, progress=True).to(self.device).eval()
            self._raft_trans = w.transforms()
        return self._raft, self._raft_trans


# ════════════════════════════════════════════════════════════════════════════
# Per-modality inference functions
# ════════════════════════════════════════════════════════════════════════════

def run_detection(reg, bgr):
    model = reg.detection(); results = model(bgr, verbose=False, device=reg.device)[0]
    canvas = bgr.copy(); dets = []
    boxes, masks, names = results.boxes, results.masks, results.names
    if boxes is not None:
        for i, box in enumerate(boxes):
            cls_id = int(box.cls[0]); conf = float(box.conf[0])
            xyxy = box.xyxy[0].cpu().numpy().astype(int)
            label = names.get(cls_id, str(cls_id)); col = COCO_PALETTE[cls_id % len(COCO_PALETTE)].tolist()
            if masks is not None:
                mh, mw = bgr.shape[:2]
                m = cv2.resize(masks.data[i].cpu().numpy(), (mw, mh)) > 0.5
                ov = canvas.copy(); ov[m] = (np.array(col)*0.55 + canvas[m]*0.45).clip(0,255).astype(np.uint8)
                canvas = ov
            x1,y1,x2,y2 = xyxy
            cv2.rectangle(canvas,(x1,y1),(x2,y2),col,2)
            txt = f"{label} {conf:.2f}"
            (tw,th),_ = cv2.getTextSize(txt,cv2.FONT_HERSHEY_SIMPLEX,0.5,1)
            cv2.rectangle(canvas,(x1,y1-th-6),(x1+tw+4,y1),col,-1)
            cv2.putText(canvas,txt,(x1+2,y1-4),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),1,cv2.LINE_AA)
            dets.append({"class_id":cls_id,"label":label,"confidence":round(conf,3),
                         "bbox":[int(x1),int(y1),int(x2),int(y2)],"has_mask":masks is not None})
    return canvas, dets


def run_semantic_segmentation(reg, bgr):
    proc, model = reg.semantic_seg()
    pil = Image.fromarray(cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)); h,w = bgr.shape[:2]
    with torch.no_grad():
        inp = proc(images=pil, return_tensors="pt").to(reg.device)
        logits = model(**inp).logits
    seg = TF.interpolate(logits,(h,w),mode="bilinear",align_corners=False).argmax(1).squeeze(0).cpu().numpy()
    cmap = np.zeros((h,w,3),dtype=np.uint8)
    for cid in np.unique(seg): cmap[seg==cid] = ADE_PALETTE[cid % len(ADE_PALETTE)]
    return cv2.cvtColor(cmap, cv2.COLOR_RGB2BGR)


def run_depth_estimation(reg, bgr):
    proc, model = reg.depth()
    pil = Image.fromarray(cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)); h,w = bgr.shape[:2]
    with torch.no_grad():
        inp = proc(images=pil, return_tensors="pt").to(reg.device)
        pred = model(**inp).predicted_depth
    depth = TF.interpolate(pred.unsqueeze(1),(h,w),mode="bilinear",align_corners=False)\
              .squeeze().cpu().numpy()
    d_norm = (depth - depth.min()) / (depth.max() - depth.min() + 1e-5)
    vis = cv2.applyColorMap((d_norm*255).astype(np.uint8), cv2.COLORMAP_MAGMA)
    return vis, d_norm


def run_optical_flow(reg, prev, curr):
    h,w = curr.shape[:2]
    if prev is None: return np.full((h,w,3),128,dtype=np.uint8)
    raft, trans = reg.optical_flow()
    def _t(b):
        return (torch.from_numpy(cv2.cvtColor(b, cv2.COLOR_BGR2RGB))
                .permute(2,0,1).unsqueeze(0).to(reg.device))
    t1,t2 = _t(prev),_t(curr)
    ph,pw = (8-h%8)%8, (8-w%8)%8
    if ph or pw:
        t1 = TF.pad(t1,(0,pw,0,ph)); t2 = TF.pad(t2,(0,pw,0,ph))
    t1t,t2t = trans(t1,t2)
    with torch.no_grad():
        flow = raft(t1t,t2t)[-1].squeeze(0).cpu().numpy()[:,:h,:w]
    return cv2.cvtColor(flow_to_rgb(flow.transpose(1,2,0)), cv2.COLOR_RGB2BGR)


def run_bevfusion(bgr, depth_norm, detections):
    h,w = bgr.shape[:2]; fx = max(w,h)*0.9
    pts = _depth_to_pseudo_lidar(depth_norm, fx=fx, fy=fx)
    boxes_bev = _detections_to_bev_boxes(detections, depth_norm, h, w, fx=fx)
    bev = render_bev_canvas(pts, boxes_bev, canvas_size=360, max_range=50.0)
    bev = cv2.resize(bev, (w,h), interpolation=cv2.INTER_LINEAR)
    cv2.rectangle(bev,(0,0),(250,22),(0,0,0),-1)
    cv2.putText(bev,"BEVFusion MIT (ICRA'23)",(4,15),cv2.FONT_HERSHEY_SIMPLEX,0.35,(0,220,160),1)
    return bev


def run_radar_voxel_fusion(bgr, depth_norm, flow_bgr, detections):
    return simulate_radar_fusion(depth_norm, flow_bgr, detections, bgr)


# ════════════════════════════════════════════════════════════════════════════
# Original 4×2 panel composer (flat / single-image mode)
# ════════════════════════════════════════════════════════════════════════════
def compose_panel(original, detection, semantic, depth_vis, flow,
                  thermal, bev, radar_fus, detections, frame_idx, total_frames):
    CELL_W, CELL_H = 640, 360; HEADER_H = 44; BORDER = 2
    cells = [
        ("RGB — Input",                         original),
        ("YOLO11x-seg — Detection + Inst.Seg",  detection),
        ("SegFormer-B5 — Semantic Seg",          semantic),
        ("Depth-Anything-V2-Large",              depth_vis),
        ("RAFT-Large — Optical Flow",            flow),
        ("Thermal Simulation — FLIR-style",      thermal),
        ("BEVFusion MIT (ICRA'23) — BEV",        bev),
        ("RadarVoxelFusionNet (TUM)",             radar_fus),
    ]
    rows = []
    for row_i in range(4):
        row_cells = []
        for col_i in range(2):
            title, img = cells[row_i*2+col_i]
            img_r = cv2.resize(img,(CELL_W,CELL_H),interpolation=cv2.INTER_LINEAR)
            header = np.full((HEADER_H,CELL_W,3),(15,15,20),dtype=np.uint8)
            accent = {0:(0,220,160),1:(0,200,255),2:(255,180,0),3:(200,80,255)}
            cv2.putText(header,title,(10,30),cv2.FONT_HERSHEY_SIMPLEX,0.58,accent[row_i],1,cv2.LINE_AA)
            img_b = cv2.copyMakeBorder(img_r,BORDER,BORDER,BORDER,BORDER,cv2.BORDER_CONSTANT,value=(40,40,50))
            img_b = cv2.resize(img_b,(CELL_W,CELL_H))
            row_cells.append(np.vstack([header,img_b]))
        rows.append(np.hstack(row_cells))
    panel = np.vstack(rows)
    footer = np.full((52,panel.shape[1],3),(10,10,14),dtype=np.uint8)
    cc = Counter(d["label"] for d in detections)
    summary = "  ·  ".join(f"{k}: {v}" for k,v in cc.most_common(5)) or "No detections"
    cv2.putText(footer,f"Frame {frame_idx+1}/{total_frames}",(12,34),cv2.FONT_HERSHEY_SIMPLEX,0.6,(100,180,255),1)
    cv2.putText(footer,summary,(200,34),cv2.FONT_HERSHEY_SIMPLEX,0.52,(200,200,200),1)
    cv2.putText(footer,f"Objects: {len(detections)}",(panel.shape[1]-200,34),cv2.FONT_HERSHEY_SIMPLEX,0.55,(80,230,140),1)
    panel = np.vstack([panel,footer])
    tbar = np.full((52,panel.shape[1],3),(8,8,12),dtype=np.uint8)
    cv2.putText(tbar,"MULTIMODAL PERCEPTION  |  YOLO11x · SegFormer · DepthV2 · RAFT · BEVFusion · RadarVoxelFusionNet",
                (16,34),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,200,255),1)
    return np.vstack([tbar,panel])


# ════════════════════════════════════════════════════════════════════════════
# GIF creator
# ════════════════════════════════════════════════════════════════════════════
def save_gif(frame_paths: list[Path], out_path: Path,
             fps: int = 4, max_width: int = 1280) -> None:
    frames_pil = []
    for p in frame_paths:
        img = cv2.imread(str(p))
        if img is None: continue
        h,w = img.shape[:2]
        if w > max_width:
            img = cv2.resize(img,(max_width,int(h*max_width/w)),interpolation=cv2.INTER_AREA)
        frames_pil.append(Image.fromarray(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
                          .convert("P",palette=Image.ADAPTIVE,colors=256))
    if not frames_pil: print("  [GIF] No frames."); return
    frames_pil[0].save(str(out_path),save_all=True,append_images=frames_pil[1:],
                       duration=int(1000/fps),loop=0,optimize=True)
    print(f"  [GIF] → {out_path}  ({len(frames_pil)} frames, {out_path.stat().st_size//1024} KB, {fps} fps)")


def collect_images(input_path: str) -> list[Path]:
    p = Path(input_path)
    if p.is_file():
        if p.suffix.lower() in IMG_EXTS: return [p]
        raise ValueError(f"Unsupported: {p}")
    if p.is_dir():
        imgs = sorted(f for f in p.iterdir() if f.suffix.lower() in IMG_EXTS)
        if not imgs: raise ValueError(f"No images in: {p}")
        return imgs
    raise ValueError(f"Path not found: {p}")


# ════════════════════════════════════════════════════════════════════════════
# 6-camera collage pipeline
# ════════════════════════════════════════════════════════════════════════════
def run_pipeline_collage(
    flat_rgb_dir:   str,
    collage_index:  str,
    output_dir:     str  = "outputs",
    device:         str  = "auto",
    gif_fps:        int  = 4,
    gif_max_w:      int  = 1920,
    cache_dir:      Optional[str] = None,
    skip_flow:      bool = False,
) -> dict:
    """
    6-camera collage mode. Reads collage_index.json produced by
    prepare_inference_inputs.py, processes all 6 cameras per timestamp,
    and produces one collage image + GIF per modality.

    Output GIFs:
        gifs/collage_rgb.gif               — 6-cam RGB input
        gifs/collage_detection.gif         — 6-cam YOLO detections
        gifs/collage_semantic.gif          — 6-cam SegFormer semantic
        gifs/collage_depth.gif             — 6-cam depth maps
        gifs/collage_flow.gif              — 6-cam optical flow
        gifs/collage_thermal.gif           — 6-cam thermal simulation
        gifs/collage_bev.gif               — 6-cam BEV (one per front cam)
        gifs/collage_radar.gif             — 6-cam radar fusion
        gifs/collage_all_modalities.gif    — 8-modality 4×2 panel for CAM_FRONT
    """
    t0 = time.time()

    if device == "auto":
        device = ("cuda" if torch.cuda.is_available()
                  else "mps" if torch.backends.mps.is_available()
                  else "cpu")

    # ── Helper: pretty progress bar ──────────────────────────────────────
    def _term_width():
        try:
            import shutil
            return shutil.get_terminal_size().columns
        except Exception:
            return 80

    def _format_eta(seconds):
        if seconds < 0 or seconds > 360000:
            return "--:--"
        m, s = divmod(int(seconds), 60)
        h, m = divmod(m, 60)
        return f"{h}h{m:02d}m{s:02d}s" if h else (f"{m}m{s:02d}s" if m else f"{s}s")

    def _print_progress(current, total, ts_idx, cam_name, step_name,
                        dets_so_far, elapsed_so_far):
        """Overwrite terminal line with a rich progress bar."""
        tw  = _term_width()
        pct = current / max(total, 1)

        # Time estimates
        if current > 0:
            eta = (elapsed_so_far / current) * (total - current)
        else:
            eta = 0
        speed = current / max(elapsed_so_far, 0.01)

        # Build bar
        BAR_W  = min(30, tw // 4)
        filled = int(BAR_W * pct)
        bar    = "█" * filled + "░" * (BAR_W - filled)

        # Compose line
        line = (f"  [{bar}] {pct*100:5.1f}%  "
                f"│ TS {ts_idx+1:>2d}/{n_timestamps}  "
                f"│ {cam_name:<16s} "
                f"│ {step_name:<10s} "
                f"│ Dets: {dets_so_far:<5d} "
                f"│ {speed:.2f} img/s  "
                f"│ ETA: {_format_eta(eta)}")
        # Pad / truncate to terminal width
        line = line[:tw-1].ljust(tw-1)
        sys.stdout.write(f"\r{line}")
        sys.stdout.flush()
    # ────────────────────────────────────────────────────────────────────

    # Opening banner
    print(f"\n{'═'*68}")
    print(f"  MULTIMODAL PERCEPTION — 6-Camera Collage Pipeline")
    print(f"  Device : {device.upper()}")
    print(f"{'═'*68}")

    # Load collage index
    with open(collage_index) as f:
        index = json.load(f)
    n_timestamps = len(index)
    total_images = n_timestamps * 6
    print(f"  Timestamps : {n_timestamps}")
    print(f"  Cameras    : {len(CAM_ORDER)}")
    print(f"  Total imgs : {total_images}")
    print(f"{'─'*68}")

    out = Path(output_dir); out.mkdir(parents=True, exist_ok=True)
    frames_dir  = out / "collage_frames"; frames_dir.mkdir(exist_ok=True)
    gifs_dir    = out / "gifs";           gifs_dir.mkdir(exist_ok=True)
    results_dir = out / "results";        results_dir.mkdir(exist_ok=True)

    # Modality output dirs (one collage image per timestamp per modality)
    mod_dirs = {}
    for mod in ["rgb","detection","semantic","depth","flow","thermal","bev","radar"]:
        d = frames_dir / mod; d.mkdir(exist_ok=True); mod_dirs[mod] = d

    reg = ModelRegistry(device=device, cache_dir=cache_dir)
    print(f"\n  ⏳ Loading models …")
    model_steps = [
        ("YOLO11x-seg",           lambda: reg.detection()),
        ("SegFormer-B5",          lambda: reg.semantic_seg()),
        ("Depth-Anything-V2-L",   lambda: reg.depth()),
    ]
    if n_timestamps > 1 and not skip_flow:
        model_steps.append(("RAFT-Large", lambda: reg.optical_flow()))
    for mi, (mname, mfn) in enumerate(model_steps, 1):
        print(f"    [{mi}/{len(model_steps)}] {mname} … ", end="", flush=True)
        mt = time.time(); mfn(); print(f"✓  ({time.time()-mt:.1f}s)")
    print(f"  ✅ All {len(model_steps)} models loaded.\n")
    print(f"{'─'*68}")
    print(f"  ▶ Starting inference …\n")

    # Track prev frame per camera for optical flow
    prev_bgr: dict[str, Optional[np.ndarray]] = {cam: None for cam in CAM_ORDER}

    # Collage frame paths per modality (for GIF assembly)
    mod_paths: dict[str, list[Path]] = {mod: [] for mod in mod_dirs}
    front_panel_paths: list[Path] = []    # 4×2 panel for CAM_FRONT (for the master GIF)
    all_dets = []
    images_done = 0          # counter for the overall progress bar

    STEP_NAMES = ["Det", "Seg", "Depth", "Flow", "Therm", "BEV", "Radar"]

    for ts_entry in index:
        t_idx = ts_entry["timestamp"]
        cam_map = ts_entry["cameras"]   # {cam_name: file_path}

        # ---------- Process each camera ----------
        results_per_cam: dict[str, dict] = {}
        for cam_i, cam in enumerate(CAM_ORDER):
            img_path = cam_map.get(cam)
            if img_path is None or not Path(img_path).exists():
                results_per_cam[cam] = None
                images_done += 1
                continue

            bgr = cv2.imread(img_path)
            if bgr is None:
                results_per_cam[cam] = None
                images_done += 1
                continue

            elapsed_now = time.time() - t0

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[0], len(all_dets), elapsed_now)
            det_vis,  dets    = run_detection(reg, bgr)

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[1], len(all_dets), time.time()-t0)
            sem_vis           = run_semantic_segmentation(reg, bgr)

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[2], len(all_dets), time.time()-t0)
            dep_vis,  dep_norm = run_depth_estimation(reg, bgr)

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[3], len(all_dets), time.time()-t0)
            flow_vis = (np.full(bgr.shape, 128, dtype=np.uint8)
                        if (skip_flow or (t_idx == 0 and n_timestamps == 1) or prev_bgr[cam] is None)
                        else run_optical_flow(reg, prev_bgr[cam], bgr))

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[4], len(all_dets), time.time()-t0)
            thermal_vis = depth_to_thermal(dep_norm, bgr)

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[5], len(all_dets), time.time()-t0)
            bev_vis     = run_bevfusion(bgr, dep_norm, dets)

            _print_progress(images_done, total_images, t_idx, cam,
                            STEP_NAMES[6], len(all_dets), time.time()-t0)
            radar_vis   = run_radar_voxel_fusion(bgr, dep_norm, flow_vis, dets)

            prev_bgr[cam] = bgr.copy()
            all_dets.extend(dets)
            images_done += 1

            results_per_cam[cam] = {
                "rgb":       bgr,
                "detection": det_vis,
                "semantic":  sem_vis,
                "depth":     dep_vis,
                "flow":      flow_vis,
                "thermal":   thermal_vis,
                "bev":       bev_vis,
                "radar":     radar_vis,
                "dets":      dets,
                "dep_norm":  dep_norm,
            }

        # Update bar after all 6 cams
        _print_progress(images_done, total_images, t_idx, "Collage",
                        "Save", len(all_dets), time.time()-t0)

        # ---------- Build 6-cam collage per modality ----------
        MODALITY_LABELS = {
            "rgb":       "RGB Input",
            "detection": "YOLO11x-seg — Detection + Instance Seg",
            "semantic":  "SegFormer-B5 — Semantic Segmentation",
            "depth":     "Depth-Anything-V2-Large — Monocular Depth",
            "flow":      "RAFT-Large — Optical Flow",
            "thermal":   "Thermal Simulation — FLIR-style INFERNO",
            "bev":       "BEVFusion MIT (ICRA'23) — Bird's Eye View",
            "radar":     "RadarVoxelFusionNet (TUM) — Radar Fusion",
        }

        for mod, label in MODALITY_LABELS.items():
            cam_imgs = {
                cam: (results_per_cam[cam][mod] if results_per_cam.get(cam) is not None else None)
                for cam in CAM_ORDER
            }
            collage = build_6cam_collage(cam_imgs, label, t_idx, n_timestamps)
            p = mod_dirs[mod] / f"{t_idx:04d}_{mod}_collage.jpg"
            cv2.imwrite(str(p), collage, [cv2.IMWRITE_JPEG_QUALITY, 90])
            mod_paths[mod].append(p)

        # ---------- 4×2 master panel for CAM_FRONT ----------
        front_res = results_per_cam.get("CAM_FRONT")
        if front_res is not None:
            master = compose_panel(
                original=front_res["rgb"], detection=front_res["detection"],
                semantic=front_res["semantic"], depth_vis=front_res["depth"],
                flow=front_res["flow"], thermal=front_res["thermal"],
                bev=front_res["bev"], radar_fus=front_res["radar"],
                detections=front_res["dets"], frame_idx=t_idx, total_frames=n_timestamps,
            )
            pp = frames_dir / f"{t_idx:04d}_front_panel.jpg"
            cv2.imwrite(str(pp), master, [cv2.IMWRITE_JPEG_QUALITY, 92])
            front_panel_paths.append(pp)

        # Per-timestamp JSON
        ts_summary = {
            "timestamp": t_idx,
            "cameras_processed": [c for c in CAM_ORDER if results_per_cam.get(c) is not None],
            "total_detections": sum(len(r["dets"]) for r in results_per_cam.values() if r),
        }
        with open(results_dir / f"{t_idx:04d}_results.json", "w") as f:
            json.dump(ts_summary, f, indent=2)

        # Print per-timestamp summary line
        ts_dets = sum(len(r["dets"]) for r in results_per_cam.values() if r)
        cams_ok = sum(1 for r in results_per_cam.values() if r is not None)
        ts_elapsed = time.time() - t0
        sys.stdout.write("\r" + " " * _term_width() + "\r")   # clear progress line
        print(f"  ✓ TS {t_idx+1:>2d}/{n_timestamps}  │  "
              f"{cams_ok}/6 cams  │  {ts_dets:>3d} dets  │  "
              f"Elapsed: {_format_eta(ts_elapsed)}")

    # ---------- Generate GIFs — one per modality + master ----------
    print(f"\n{'─'*68}")
    print(f"  🎞  Generating GIFs ({n_timestamps} timestamps) …")
    gif_paths = {}
    gif_items = list(mod_paths.items())
    for gi, (mod, paths) in enumerate(gif_items, 1):
        if not paths: continue
        gp = gifs_dir / f"collage_{mod}.gif"
        print(f"    [{gi}/{len(gif_items)}] collage_{mod}.gif … ", end="", flush=True)
        save_gif(paths, gp, fps=gif_fps, max_width=gif_max_w)
        gif_paths[f"collage_{mod}"] = str(gp)

    if front_panel_paths:
        gp = gifs_dir / "collage_all_modalities_front.gif"
        print(f"    [Master] collage_all_modalities_front.gif … ", end="", flush=True)
        save_gif(front_panel_paths, gp, fps=gif_fps, max_width=gif_max_w)
        gif_paths["collage_all_modalities_front"] = str(gp)

    # Summary
    elapsed = time.time() - t0
    label_counts = Counter(d["label"] for d in all_dets)
    summary = {
        "mode": "6-camera collage",
        "timestamps": n_timestamps,
        "cameras": CAM_ORDER,
        "total_detections": len(all_dets),
        "class_counts": dict(label_counts.most_common()),
        "gifs_generated": len(gif_paths),
        "gif_paths": gif_paths,
        "elapsed_seconds": round(elapsed, 2),
        "device": device,
    }
    with open(out / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    # Final summary banner
    topN = label_counts.most_common(5)
    det_summary = "  ·  ".join(f"{k}: {v}" for k, v in topN) if topN else "none"
    print(f"\n{'═'*68}")
    print(f"  ✅  PIPELINE COMPLETE")
    print(f"{'─'*68}")
    print(f"  Timestamps  : {n_timestamps}")
    print(f"  Images      : {total_images}  ({total_images} processed)")
    print(f"  Detections  : {len(all_dets)}")
    print(f"  Top classes : {det_summary}")
    print(f"  GIFs        : {len(gif_paths)}  →  {gifs_dir}/")
    print(f"  Elapsed     : {_format_eta(elapsed)}  ({elapsed:.1f}s)")
    print(f"  Avg speed   : {total_images/max(elapsed,0.01):.2f} img/s")
    print(f"  Output dir  : {out.resolve()}")
    print(f"{'═'*68}\n")
    return summary


# ════════════════════════════════════════════════════════════════════════════
# Original flat pipeline (single-image / flat folder mode)
# ════════════════════════════════════════════════════════════════════════════
def run_pipeline(
    input_path:  str,
    output_dir:  str  = "outputs",
    device:      str  = "auto",
    gif_fps:     int  = 4,
    gif_max_w:   int  = 1280,
    cache_dir:   Optional[str] = None,
    skip_flow:   bool = False,
) -> dict:
    t0 = time.time()
    if device == "auto":
        device = ("cuda" if torch.cuda.is_available()
                  else "mps" if torch.backends.mps.is_available()
                  else "cpu")
    print(f"[Pipeline] Device: {device.upper()}")

    out = Path(output_dir); out.mkdir(parents=True, exist_ok=True)
    frames_dir  = out / "frames";     frames_dir.mkdir(exist_ok=True)
    results_dir = out / "results";    results_dir.mkdir(exist_ok=True)
    gifs_dir    = out / "gifs";       gifs_dir.mkdir(exist_ok=True)
    bev_dir     = out / "bev_frames"; bev_dir.mkdir(exist_ok=True)
    radar_dir   = out / "radar_frames"; radar_dir.mkdir(exist_ok=True)

    image_paths = collect_images(input_path); n = len(image_paths)
    print(f"[Pipeline] {n} image(s)  ·  output → {out.resolve()}\n")

    reg = ModelRegistry(device=device, cache_dir=cache_dir)
    print("[Pipeline] Loading models …")
    reg.detection(); reg.semantic_seg(); reg.depth()
    if n > 1 and not skip_flow: reg.optical_flow()
    print("[Pipeline] All models ready.\n")

    all_dets = []; panel_paths = []; bev_paths = []; radar_paths = []; prev_bgr = None

    for idx, img_path in enumerate(tqdm(image_paths, desc="Inference", unit="frame")):
        bgr = cv2.imread(str(img_path))
        if bgr is None: print(f"  [WARN] Cannot read {img_path}"); continue
        stem = f"{idx:04d}_{img_path.stem}"

        det_vis,  dets    = run_detection(reg, bgr)
        sem_vis           = run_semantic_segmentation(reg, bgr)
        dep_vis,  dep_norm = run_depth_estimation(reg, bgr)

        flow_vis = (np.full(bgr.shape,128,dtype=np.uint8)
                    if (skip_flow or (idx==0 and n==1) or prev_bgr is None)
                    else run_optical_flow(reg, prev_bgr, bgr))

        thermal_vis = depth_to_thermal(dep_norm, bgr)
        bev_vis     = run_bevfusion(bgr, dep_norm, dets)
        radar_vis   = run_radar_voxel_fusion(bgr, dep_norm, flow_vis, dets)

        panel = compose_panel(
            original=bgr, detection=det_vis, semantic=sem_vis,
            depth_vis=dep_vis, flow=flow_vis, thermal=thermal_vis,
            bev=bev_vis, radar_fus=radar_vis,
            detections=dets, frame_idx=idx, total_frames=n,
        )
        pp = frames_dir / f"{stem}_panel.jpg"
        cv2.imwrite(str(pp), panel, [cv2.IMWRITE_JPEG_QUALITY, 92]); panel_paths.append(pp)

        cv2.imwrite(str(results_dir/f"{stem}_1_rgb_detection.jpg"), det_vis)
        cv2.imwrite(str(results_dir/f"{stem}_2_semantic_seg.jpg"),  sem_vis)
        cv2.imwrite(str(results_dir/f"{stem}_3_depth.jpg"),          dep_vis)
        cv2.imwrite(str(results_dir/f"{stem}_4_optical_flow.jpg"),   flow_vis)
        cv2.imwrite(str(results_dir/f"{stem}_5_thermal.jpg"),        thermal_vis)
        cv2.imwrite(str(results_dir/f"{stem}_6_bevfusion_bev.jpg"),  bev_vis)
        cv2.imwrite(str(results_dir/f"{stem}_7_radar_fusion.jpg"),   radar_vis)

        bvp = bev_dir / f"{stem}_bev.jpg"; rdp = radar_dir / f"{stem}_radar.jpg"
        cv2.imwrite(str(bvp), bev_vis); bev_paths.append(bvp)
        cv2.imwrite(str(rdp), radar_vis); radar_paths.append(rdp)

        with open(results_dir/f"{stem}_results.json","w") as f:
            json.dump({"frame":idx,"source":str(img_path),"detections":dets,
                       "detection_count":len(dets),
                       "depth_stats":{"min":float(dep_norm.min()),
                                      "max":float(dep_norm.max()),
                                      "mean":float(dep_norm.mean())}}, f, indent=2)
        all_dets.extend(dets); prev_bgr = bgr.copy()

    gif_paths: dict = {}
    if panel_paths:
        print(f"\n[GIF] Generating GIFs from {len(panel_paths)} frame(s) …")
        save_gif(panel_paths, gifs_dir/"scene_all_modalities.gif", fps=gif_fps, max_width=gif_max_w)
        save_gif(bev_paths,   gifs_dir/"scene_bevfusion.gif",      fps=gif_fps, max_width=gif_max_w//2)
        save_gif(radar_paths, gifs_dir/"scene_radar_fusion.gif",   fps=gif_fps, max_width=gif_max_w//2)
        gif_paths = {
            "all_modalities": str((gifs_dir/"scene_all_modalities.gif").resolve()),
            "bevfusion":      str((gifs_dir/"scene_bevfusion.gif").resolve()),
            "radar_fusion":   str((gifs_dir/"scene_radar_fusion.gif").resolve()),
        }

    elapsed = time.time() - t0
    label_counts = Counter(d["label"] for d in all_dets)
    summary = {
        "total_frames": n, "frames_processed": len(panel_paths),
        "total_detections": len(all_dets), "class_counts": dict(label_counts.most_common()),
        "elapsed_seconds": round(elapsed,2),
        "fps": round(len(panel_paths)/elapsed,2) if elapsed and panel_paths else 0,
        "device": device, "output_dir": str(out.resolve()), "gifs": gif_paths,
    }
    with open(out/"summary.json","w") as f: json.dump(summary,f,indent=2)

    print(f"\n{'═'*68}")
    print(f"  DONE  —  {len(panel_paths)}/{n} frame(s)  ·  {elapsed:.1f}s  ·  "
          f"{summary['fps']:.2f} fps  ·  {len(all_dets)} detections")
    if panel_paths: print(f"  GIFs  →  {gifs_dir}/")
    print(f"{'═'*68}\n")
    return summary


# ════════════════════════════════════════════════════════════════════════════
# CLI
# ════════════════════════════════════════════════════════════════════════════
def _cli():
    p = argparse.ArgumentParser(
        description="7-head Multimodal Perception — flat or 6-cam collage mode",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Flat mode (single image or folder):
  python inference_pipeline_fixed.py --input photo.jpg
  python inference_pipeline_fixed.py --input ./frames/ --gif-fps 6

  # 6-camera collage mode (use after prepare_inference_inputs.py):
  python inference_pipeline_fixed.py \\
      --input  D:/Mtech/Sem_4/output/inference/input/flat_rgb/ \\
      --collage-index D:/Mtech/Sem_4/output/inference/input/collage_index.json \\
      --output D:/Mtech/Sem_4/output/inference/output/ \\
      --device cuda --gif-fps 4
        """)
    p.add_argument("--input",         required=True)
    p.add_argument("--output",        default=r"D:\Mtech\Sem_4\output\inference\output")
    p.add_argument("--collage-index", default=None,
                   help="Path to collage_index.json — enables 6-cam collage mode")
    p.add_argument("--device",        default="auto", choices=["auto","cuda","mps","cpu"])
    p.add_argument("--gif-fps",       type=int, default=4)
    p.add_argument("--gif-max-w",     type=int, default=1920)
    p.add_argument("--cache-dir",     default=None)
    p.add_argument("--skip-flow",     action="store_true")
    args = p.parse_args()

    if args.collage_index:
        run_pipeline_collage(
            flat_rgb_dir  = args.input,
            collage_index = args.collage_index,
            output_dir    = args.output,
            device        = args.device,
            gif_fps       = args.gif_fps,
            gif_max_w     = args.gif_max_w,
            cache_dir     = args.cache_dir,
            skip_flow     = args.skip_flow,
        )
    else:
        run_pipeline(
            input_path = args.input,
            output_dir = args.output,
            device     = args.device,
            gif_fps    = args.gif_fps,
            gif_max_w  = args.gif_max_w,
            cache_dir  = args.cache_dir,
            skip_flow  = args.skip_flow,
        )


if __name__ == "__main__":
    _cli()
